/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sinoantonimo;

import javax.swing.ButtonGroup;
/**
 *
 * @author carlos mila
 */
public class VentanaTest extends javax.swing.JFrame {

    ButtonGroup respuesta1 = new ButtonGroup();
    ButtonGroup respuesta2 = new ButtonGroup();
    ButtonGroup respuesta3 = new ButtonGroup();
    ButtonGroup respuesta4 = new ButtonGroup();
    ButtonGroup respuesta5 = new ButtonGroup();
    ButtonGroup respuesta6 = new ButtonGroup();
    ButtonGroup respuesta7 = new ButtonGroup();
    ButtonGroup respuesta8 = new ButtonGroup();
    ButtonGroup respuesta9 = new ButtonGroup();
    ButtonGroup respuesta10 = new ButtonGroup(); // un grupo que almacena las 10 respuestas que se van a manejar en el juego
    
    /**
     * Creates new form VentanaTest
     */
    
    
    
    public VentanaTest() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        /**
         * Inicializa la ventana de Bienvenida
         */
        VentanaBienvenida ventana = new VentanaBienvenida();
        txtImpNombre.setText(ventana.nombrejugador); // aca se llama la clase publica de la ventana anterior para mostrar el nombre que se introdujo en el cuadro de texto de la ventana anterior.
        
        /**
         * Agrega las opciones de respuesta a los grupos de botones.
         * mediante las opciones que se despliegan en las ventanas 
         * se indica que solo se puede escoger una unica respuesta por pregunta realizada.
         */
        respuesta1.add(Rta11);
        respuesta1.add(Rta12);
        
        respuesta2.add(Rta21);
        respuesta2.add(Rta22);
        
        respuesta3.add(Rta31);
        respuesta3.add(Rta32);
        
        respuesta4.add(Rta41);
        respuesta4.add(Rta42);
        
        respuesta5.add(Rta51);
        respuesta5.add(Rta52);
        
        respuesta6.add(Rta61);
        respuesta6.add(Rta62);
        
        respuesta7.add(Rta71);
        respuesta7.add(Rta72);
        
        respuesta8.add(Rta81);
        respuesta8.add(Rta82);
        
        respuesta9.add(Rta91);
        respuesta9.add(Rta92);
        
        respuesta10.add(Rta101);
        respuesta10.add(Rta102);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	/**
    	 * Inicialización de todos los componentes visuales de la aplicación
    	 */
        jLabel3 = new javax.swing.JLabel();
        txtImpNombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pregunta1 = new javax.swing.JLabel();
        Rta11 = new javax.swing.JRadioButton();
        Rta12 = new javax.swing.JRadioButton();
        Pregunta2 = new javax.swing.JLabel();
        Rta21 = new javax.swing.JRadioButton();
        Rta22 = new javax.swing.JRadioButton();
        Pregunta3 = new javax.swing.JLabel();
        Rta31 = new javax.swing.JRadioButton();
        Rta32 = new javax.swing.JRadioButton();
        Pregunta4 = new javax.swing.JLabel();
        Rta41 = new javax.swing.JRadioButton();
        Rta42 = new javax.swing.JRadioButton();
        Pregunta5 = new javax.swing.JLabel();
        Rta51 = new javax.swing.JRadioButton();
        Rta52 = new javax.swing.JRadioButton();
        Pregunta9 = new javax.swing.JLabel();
        Rta91 = new javax.swing.JRadioButton();
        Rta92 = new javax.swing.JRadioButton();
        Pregunta10 = new javax.swing.JLabel();
        Pregunta6 = new javax.swing.JLabel();
        Rta101 = new javax.swing.JRadioButton();
        Rta61 = new javax.swing.JRadioButton();
        Rta102 = new javax.swing.JRadioButton();
        Rta62 = new javax.swing.JRadioButton();
        Pregunta7 = new javax.swing.JLabel();
        Rta71 = new javax.swing.JRadioButton();
        Pregunta8 = new javax.swing.JLabel();
        Rta72 = new javax.swing.JRadioButton();
        Rta81 = new javax.swing.JRadioButton();
        Rta82 = new javax.swing.JRadioButton();
        ButtonResultados = new javax.swing.JButton();
        TextoResultados = new javax.swing.JLabel();

        /**
         * Define la operación de cierre de la ventana
         */
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        /**
         * Establece estilos de fuente para los label
         */
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel3.setText("Hola Jugador");

        txtImpNombre.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        txtImpNombre.setText("jLabel1");

        /**
         * Definición para el botón de regresar
         */
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        /**
         * Se agregan las palabras al menu de las preguntas
         */
        jLabel1.setText("A continuaciÃ³n encontrarÃ¡ diez preguntas sobre sinÃ³nimos, por favor escoja la correcta.");

        pregunta1.setText("A trochemoche");

        Rta11.setText("Disparatadamente");

        Rta12.setText("Anticipadamente");

        Pregunta2.setText("AbacÃ¡");

        Rta21.setText("Lienzo");
        Rta21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rta21ActionPerformed(evt);
            }
        });

        Rta22.setText("Cabuya");

        Pregunta3.setText("Buzonera");

        Rta31.setSelected(true);
        Rta31.setText("Conducto");

        Rta32.setText("Armario");

        Pregunta4.setText("CebÃ³n");

        Rta41.setText("Velas");

        Rta42.setText("Cerdo");

        Pregunta5.setText("Jaca");

        Rta51.setText("Caballo");

        Rta52.setText("Ã�guila");

        Pregunta9.setText("PÃ¡bilo");

        Rta91.setText("Mecha");

        Rta92.setText("Trapo");

        Pregunta10.setText("LÃ¡bil");

        Pregunta6.setText("A ultranza");

        Rta101.setText("FrÃ¡gil");

        Rta61.setText("Resueltamente");

        Rta102.setText("Fuerte");

        Rta62.setText("IndecisiÃ³n");

        Pregunta7.setText("Kiosco");

        Rta71.setText("Garita");

        Pregunta8.setText("Macelo");

        Rta72.setText("Terreno");

        Rta81.setText("BaÃ±o");

        Rta82.setText("Degolladero");

        ButtonResultados.setText("Ver Resultados");
        ButtonResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResultadosActionPerformed(evt);
            }
        });

        TextoResultados.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(ButtonResultados)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Pregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Pregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtImpNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jButton1)
                                                .addComponent(pregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Pregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(Rta31)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Rta32))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(Rta21)
                                                        .addGap(78, 78, 78)
                                                        .addComponent(Rta22)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(Rta51)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Rta52))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(Rta41)
                                                        .addGap(81, 81, 81)
                                                        .addComponent(Rta42))))
                                            .addGap(50, 50, 50))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(Rta11)
                                            .addGap(18, 18, 18)
                                            .addComponent(Rta12)))
                                    .addComponent(Pregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Pregunta8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Rta81)
                                                .addGap(41, 41, 41)
                                                .addComponent(Rta82))
                                            .addComponent(Pregunta10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Pregunta6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Rta61)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Rta62))
                                            .addComponent(Pregunta7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Rta71)
                                                .addGap(34, 34, 34)
                                                .addComponent(Rta72))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Rta101)
                                                .addGap(41, 41, 41)
                                                .addComponent(Rta102))
                                            .addComponent(Rta91))
                                        .addGap(119, 119, 119))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Rta92)
                                        .addComponent(Pregunta9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(TextoResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtImpNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pregunta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rta11)
                            .addComponent(Rta12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pregunta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rta21)
                            .addComponent(Rta22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pregunta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rta31)
                            .addComponent(Rta32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pregunta4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rta41)
                            .addComponent(Rta42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pregunta5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rta51)
                            .addComponent(Rta52)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pregunta6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rta61)
                            .addComponent(Rta62))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pregunta7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rta71)
                            .addComponent(Rta72))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pregunta8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rta81)
                            .addComponent(Rta82))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pregunta9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rta91)
                            .addComponent(Rta92))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pregunta10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rta101)
                            .addComponent(Rta102))))
                .addGap(18, 18, 18)
                .addComponent(ButtonResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * esta acción indica que al momento de hacer clic en regresar, 
     * la ventana actual se oculta para volver a la ventana anterior
     * @param evt Evento de la acción del botón
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaBienvenida regresar = new VentanaBienvenida();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Rta21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rta21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rta21ActionPerformed

    /**
     * Método que evalua el resultado del juego
     * @param evt Evento de entrada del clic del botón
     */
    private void ButtonResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResultadosActionPerformed
        // TODO add your handling code here:
    	
    	/**
    	 * mediante las condicionales se programan las respuestas 
    	 * y se realiza la suma del puntaje segÃºin las opciones escogidas.
    	 */
        
        int puntaje = 0;
        String resultados="";
        
        if(Rta11.isSelected()){
        puntaje = puntaje + 1;
        } else{
            if (Rta12.isSelected()){
                puntaje = puntaje;
            }
        }
        
        if(Rta21.isSelected()){
        puntaje = puntaje;
        }
        else{
            if (Rta22.isSelected()){
                puntaje = puntaje + 1;
            }
        }
        
        
        if(Rta31.isSelected()){
        puntaje = puntaje + 1;
        }
        else{
            if (Rta32.isSelected()){
                puntaje = puntaje;
            }
        }
        
        
        if(Rta41.isSelected()){
        puntaje = puntaje;
        }
        else{
            if (Rta42.isSelected()){
                puntaje = puntaje + 1;
            }
        }
        
        if(Rta51.isSelected()){
        puntaje = puntaje + 1;
        }
        else{
            if (Rta52.isSelected()){
                puntaje = puntaje;
            }
        }
        if(Rta61.isSelected()){
        puntaje = puntaje + 1;
        }
        else{
            if (Rta62.isSelected()){
                puntaje = puntaje;
            }
        }
        if(Rta71.isSelected()){
        puntaje = puntaje + 1;
        }
        else{
            if (Rta72.isSelected()){
                puntaje = puntaje;
            }
        }
        if(Rta81.isSelected()){
        puntaje = puntaje;
        }
        else{
            if (Rta82.isSelected()){
                puntaje = puntaje + 1;
            }
        }
        if(Rta91.isSelected()){
        puntaje = puntaje + 1;
        }
        else{
            if (Rta92.isSelected()){
                puntaje = puntaje;
            }
        }
        if(Rta101.isSelected()){
        puntaje = puntaje + 1;
        }
        else{
            if (Rta102.isSelected()){
                puntaje = puntaje;
            }
        }
        
        if (puntaje>=8){
            resultados ="Eres el gurÃº del idioma espaÃ±ol";
        }
        else resultados ="Debes estudiar un poco mas";

        /**
         * Se concatena y se escribe el resultado. 
         * La prueba se pasa si el puntaje es mayor o igual a 8
         */
        TextoResultados.setText(""+resultados);
        
        
        
        
        
        
        
    }//GEN-LAST:event_ButtonResultadosActionPerformed

    /**
     * Método de entrada de la clase
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonResultados;
    private javax.swing.JLabel Pregunta10;
    private javax.swing.JLabel Pregunta2;
    private javax.swing.JLabel Pregunta3;
    private javax.swing.JLabel Pregunta4;
    private javax.swing.JLabel Pregunta5;
    private javax.swing.JLabel Pregunta6;
    private javax.swing.JLabel Pregunta7;
    private javax.swing.JLabel Pregunta8;
    private javax.swing.JLabel Pregunta9;
    private javax.swing.JRadioButton Rta101;
    private javax.swing.JRadioButton Rta102;
    private javax.swing.JRadioButton Rta11;
    private javax.swing.JRadioButton Rta12;
    private javax.swing.JRadioButton Rta21;
    private javax.swing.JRadioButton Rta22;
    private javax.swing.JRadioButton Rta31;
    private javax.swing.JRadioButton Rta32;
    private javax.swing.JRadioButton Rta41;
    private javax.swing.JRadioButton Rta42;
    private javax.swing.JRadioButton Rta51;
    private javax.swing.JRadioButton Rta52;
    private javax.swing.JRadioButton Rta61;
    private javax.swing.JRadioButton Rta62;
    private javax.swing.JRadioButton Rta71;
    private javax.swing.JRadioButton Rta72;
    private javax.swing.JRadioButton Rta81;
    private javax.swing.JRadioButton Rta82;
    private javax.swing.JRadioButton Rta91;
    private javax.swing.JRadioButton Rta92;
    private javax.swing.JLabel TextoResultados;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel pregunta1;
    private javax.swing.JLabel txtImpNombre;
    // End of variables declaration//GEN-END:variables
}
